### ISSUE TITLE
Problem on Line 94

### ISSUE THREAD

**Issue by thunder-birds** [jasondinh/CaptCharmander#1]
response = requests.get('http://2captcha.com/res.php?key='+captcha_key+'&action=get&id='+captcha_id)

to

response = requests.get('http://2captcha.com/res.php?key='+twocaptcha_key+'&action=get&id='+captcha_id)

**Comment by Rook25** [comment]
Thanksf or this. I've made that change but am still getting issues with it not actually completing a captcha. it sends away the request to 2captcha but receives no response and then loops back to try to login to the captcha'd account.

**Comment by jasondinh** [comment]
I changed a variable name before pushing without checking again. Fixed.
