### ISSUE TITLE
Can't log into PTC

### ISSUE THREAD

**Issue by 6spdvtec** [jasondinh/CaptCharmander#2]
I can log into my PTC accounts on the website and the game, but this script can't log into any of them. I set lat, long and alt in the configuration part.

**Comment by jasondinh** [comment]
Set debug=True and paste your output here (please remove personal info)

**Comment by 6spdvtec** [comment]
Loop number 1 of 1
Checking username1 with password password1
Trying to login with username1

Cannot login with username1, trying again
Trying to login with username1

Cannot login with username1, trying again
Trying to login with username1

Cannot login with username1, trying again
username1 failed to login

Checking username2 with password password2
Trying to login with username2

Cannot login with username2, trying again
Trying to login with username2

Cannot login with username2, trying again
Trying to login with username2

**Comment by jasondinh** [comment]
Was there any output about an exception? It's weird if this is the entire output. 

Have you run `pip install -r requirements.txt --upgrade` to install the latest `pgoapi` yet?

**Comment by 6spdvtec** [comment]
Hi. That was the entire output. I installed pogoapi from some instructions I found on github. Here is the output when I ran the command you just mentioned:

C:\Users\Administrator\Desktop\captcha\CaptCharmander>pip install -r requirements.txt --upgrade
Collecting pgoapi from git+https://github.com/pogodevorg/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 1))
  Cloning https://github.com/pogodevorg/pgoapi.git to c:\users\admini~1\appdata\local\temp\pip-build-p53pf7k7\pgoapi
Requirement already up-to-date: geopy==1.11.0 in c:\program files (x86)\python35-32\lib\site-packages (from pgoapi->-r requirements.txt (line 1))

Requirement already up-to-date: protobuf>=3.0.0a3 in c:\program files (x86)\python35-32\lib\site-packages (from pgoapi->-r requirements.txt (line
 1))
Requirement already up-to-date: requests==2.10.0 in c:\program files (x86)\python35-32\lib\site-packages (from pgoapi->-r requirements.txt (line
1))
Requirement already up-to-date: s2sphere==0.2.4 in c:\program files (x86)\python35-32\lib\site-packages (from pgoapi->-r requirements.txt (line 1
))
Collecting gpsoauth==0.4.0 (from pgoapi->-r requirements.txt (line 1))
Requirement already up-to-date: future in c:\program files (x86)\python35-32\lib\site-packages (from pgoapi->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\program files (x86)\python35-32\lib\site-packages (from pgoapi->-r requirements.txt (line 1))
Collecting xxhash (from pgoapi->-r requirements.txt (line 1))
  Using cached xxhash-0.6.1.tar.gz
Collecting setuptools (from protobuf>=3.0.0a3->pgoapi->-r requirements.txt (line 1))
  Downloading setuptools-28.8.0-py2.py3-none-any.whl (472kB)
    100% |################################| 481kB 1.9MB/s
Requirement already up-to-date: pycryptodomex>=3.0 in c:\program files (x86)\python35-32\lib\site-packages (from gpsoauth==0.4.0->pgoapi->-r requ
irements.txt (line 1))
Building wheels for collected packages: xxhash
  Running setup.py bdist_wheel for xxhash ... error
  Complete output from command "c:\program files (x86)\python35-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\
AppData\\Local\\Temp\\pip-build-p53pf7k7\\xxhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clo
se();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ADMINI~1\AppData\Local\Temp\tmpg7v_v5b3pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'xxhash' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for xxhash
  Running setup.py clean for xxhash
Failed to build xxhash
Installing collected packages: gpsoauth, xxhash, pgoapi, setuptools
  Found existing installation: gpsoauth 0.3.0
    Uninstalling gpsoauth-0.3.0:
      Successfully uninstalled gpsoauth-0.3.0
  Running setup.py install for xxhash ... error
    Complete output from command "c:\program files (x86)\python35-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1
\\AppData\\Local\\Temp\\pip-build-p53pf7k7\\xxhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.c
lose();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-iznw7vos-record\install-record.txt --sing
le-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxhash' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command ""c:\program files (x86)\python35-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\
pip-build-p53pf7k7\\xxhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code
, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-iznw7vos-record\install-record.txt --single-version-externally-ma
naged --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-p53pf7k7\xxhash\

**Comment by jasondinh** [comment]
The installation for `pgoapi` failed. Please get that sorted first. Please contact their support here https://discord.pogodev.org
