### ISSUE TITLE
Not able to run 

### ISSUE THREAD

**Issue by Zubinexu** [jasondinh/CaptCharmander#3]
1. download git
2. create account.csv file (user1,pass1,user2,pass2,etc3,etc3)
3. configure captCharmander.py with location,  2captcha key
4. pip install -r requirements.txt --upgrade 
5. debug = True
6. python captCharmander.py

this is what I get : 

Loop number 1 of 1
Sleep for 30 seconds

C:\Python27\CaptCharmander-master>

**Comment by jasondinh** [comment]
csv file should be in this format

```
user1,pass1
user2,pass2
user3,pass3
```

**Comment by Zubinexu** [comment]
Can close the issue it is working now
