### ISSUE TITLE
2captcha SyntaxError

### ISSUE THREAD

**Issue by CTMapper** [jasondinh/CaptCharmander#4]
When running, I get a SyntaxError as below.  I've cut & pasted the key directly from 2Captcha so there are no typos.  It looks like there's a carrot prompt lined up with the last character of the key.  Is there some other syntax that could be causing the error?

$ python captcharmander.py
  File "captcharmander.py", line 30
    twocaptcha_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                                                             ^
SyntaxError: invalid syntax

**Comment by jasondinh** [comment]
Did you put them in quote, eg `"abcdef1234411123"`

**Comment by CTMapper** [comment]
Thank you.  Yes, that was the problem.  I added the quotes and it now works well.  Thanks!
